spring:
  application:
    name: SpringWebFlux

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webFlux
    username: postgres
    password: 1091

  flyway:
    url: jdbc:postgresql://localhost:5432/webFlux
    user: postgres
    password: 1091

management:
  server:
    port: 8081  # отдельный порт для метрик (опционально)

  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - env
          - beans

  endpoint:
    health:
      show-details: always
      show-components: always

  metrics:
    enable:
      all: true
    export:
      prometheus: {}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        "http.server.requests": [0.5, 0.75, 0.95, 0.99]
    tags:
      application: ${spring.application.name}
      environment: local
      version: 1.0.0